repos:
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.7
          entry: bash -c 'black "$@"; git add -u' --
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.7.9
        hooks:
        - id: flake8
    -   repo: https://github.com/asottile/seed-isort-config
        rev: v2.1.1
        hooks:
        -   id: seed-isort-config
            language_version: python3.7
            entry: bash -c 'seed-isort-config "$@"; git add -u' --
    -   repo: https://github.com/timothycrosley/isort
        rev: 4.3.21
        hooks:
        -   id: isort
            language_version: python3.7
            entry: bash -c 'isort "$@"; git add -u' --